interface Records {
    id: number;
    product: string;
    farmname: string;
    cropname: string;
    date: string;
    quantity: string;
    price: string;

}

const records: Records[] = [
    {
        id: 1,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 2,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 3,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 4,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 5,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 6,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 7,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 8,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 9,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 10,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 11,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 12,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 13,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 14,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 15,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 16,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 17,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 18,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 19,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 20,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 21,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 22,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 23,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 24,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 25,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 26,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 27,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
    {
        id: 28,
        product: 'Material 1',
        farmname: 'Kaggle',
        cropname: 'Potato',
        date: '03/08/2020',
        quantity: '300',
        price: '2,15,000',
    },
];
export { records };
